name = "PCP"
version = "0.1.0"
defaultTargets = ["pcp"]



[[lean_lib]]
name = "PCP"

[[lean_lib]]
name = "CFG"


[[require]]
name = "cslib"
scope = "leanprover"
rev = "main"


[[lean_exe]]
name = "pcp"
root = "Main"


