import PCP.PCP_interface

import PCP.PCP_interface
import PCP.PCP_coq

namespace PCP

variable {α : Type}

/-!
## Phase 1: The Translation Bridge
Functions to convert between the Frontend (Tile / Instance)
and the Backend (Word pairs / Stack).
-/

/-- Convert a frontend `Tile` into a backend word pair. -/
def tileToPair (t : Tile α) : Word α × Word α :=
  (t.top, t.bot)

/-- Convert a frontend `Instance` (List of Tiles) into a backend `Stack`. -/
def instanceToStack (P : Instance α) : Stack α :=
  P.map tileToPair

/-- Convert a sequence of indices into a backend `Stack`. -/
def idxsToStack (P : Instance α) (idxs : List (Fin P.length)) : Stack α :=
  idxs.map (fun i => tileToPair (P.get i))

@[simp]
theorem tau1_idxsToStack (P : Instance α) (idxs : List (Fin P.length)) :
    tau1 (idxsToStack P idxs) = concatTop P idxs := by
  induction idxs with
  | nil => rfl
  | cons i is ih =>
    sorry -- Hint: simp [idxsToStack, concatTop] and use ih

@[simp]
theorem tau2_idxsToStack (P : Instance α) (idxs : List (Fin P.length)) :
    tau2 (idxsToStack P idxs) = concatBot P idxs := by
  induction idxs with
  | nil => rfl
  | cons i is ih =>
    sorry -- Hint: simp [idxsToStack, concatBot] and use ih

/-!
## Phase 2: PCP Equivalence
Proving that `HasSolution P ↔ PCP_coq.PCP (instanceToStack P)`
-/

/-- Forward direction: dPCP to Coq PCP -/
theorem dPCP_implies_coqPCP (P : Instance α) (h : dPCP P) :
    PCP (instanceToStack P) := by
  sorry

/-- Backward direction: Coq PCP to dPCP -/
theorem coqPCP_implies_dPCP (P : Instance α) (h : PCP (instanceToStack P)) :
    dPCP P := by
  sorry

/-- Main Equivalence for PCP -/
theorem hasSolution_iff_coqPCP (P : Instance α) :
    HasSolution P ↔ PCP (instanceToStack P) := by
  -- Hint: Route this through `hasSolution_iff_dPCP` and the two lemmas above!
  constructor
  · intro h
    apply dPCP_implies_coqPCP
    exact (hasSolution_iff_dPCP P).mp h
  · intro h
    apply (hasSolution_iff_dPCP P).mpr
    exact coqPCP_implies_dPCP P h


/-!
## Phase 3: MPCP Equivalence
Proving that `MHasSolution M ↔ PCP_coq.MPCP c₀ P_stack`
-/

/-- Extract the starting pair `c₀` from an `MInstance`. -/
def mInstanceStartPair (M : MInstance α) : Word α × Word α :=
  tileToPair (M.tiles.get M.startIdx)

/-- Forward direction: Frontend MPCP to Backend MPCP -/
theorem mHasSolution_implies_coqMPCP (M : MInstance α) (h : MHasSolution M) :
    MPCP (mInstanceStartPair M) (instanceToStack M.tiles) := by
  obtain ⟨idxs, ⟨hne, h_head, h_eq⟩⟩ := h
  -- Hint: Since `idxs ≠ []`, you can destruct it into `startIdx :: tail_idxs`.
  -- Map `tail_idxs` using `idxsToStack` to form your witness `A`.
  sorry

/-- Backward direction: Backend MPCP to Frontend MPCP -/
theorem coqMPCP_implies_mHasSolution (M : MInstance α)
    (h : MPCP (mInstanceStartPair M) (instanceToStack M.tiles)) :
    MHasSolution M := by
  obtain ⟨A, h_mem, h_eq⟩ := h
  -- Hint: Map the stack `A` back to a list of `Fin M.tiles.length` indices.
  -- Prepend `M.startIdx` to this list to form your witness `idxs`.
  sorry

/-- Main Equivalence for MPCP -/
theorem mHasSolution_iff_coqMPCP (M : MInstance α) :
    MHasSolution M ↔ MPCP (mInstanceStartPair M) (instanceToStack M.tiles) := by
  exact ⟨mHasSolution_implies_coqMPCP M, coqMPCP_implies_mHasSolution M⟩


/-Phase 4-/

def extMap : Ext α → SymbolExt α
  | .sym a  => .old a
  | .hash   => .marker
  | .dollar => .endMarker

/-- Map words and pairs between the two extension types -/
def pairMap (p : Word (Ext α) × Word (Ext α)) : Word (SymbolExt α) × Word (SymbolExt α) :=
  (p.1.map extMap, p.2.map extMap)

/--
The core structural equivalence: the stack generated by the frontend `mpcp_to_pcp`
is exactly the stack generated by the backend `mpcpToPcp`, mapped to the new symbols.
-/
theorem instanceToStack_mpcp_to_pcp (M : MInstance α) :
    instanceToStack (mpcp_to_pcp M) =
    (mpcpToPcp (mInstanceStartPair M).1 (mInstanceStartPair M).2 (instanceToStack M.tiles)).map pairMap := by
  -- Hint: unfold mpcp_to_pcp and mpcpToPcp, then use list simplifications.
  sorry

/--
The Ultimate Theorem:
The frontend MPCP instance has a solution IF AND ONLY IF
the reduced frontend PCP instance has a solution.
-/
theorem mpcp_reduction_correct (M : MInstance α) :
    MHasSolution M ↔ HasSolution (mpcp_to_pcp M) := by
  -- 1. Route MHasSolution to the backend MPCP using `mHasSolution_iff_coqMPCP`
  -- 2. Use the Coq backend reduction theorem `mpcp_iff_pcp`
  -- 3. Route the backend PCP back to the frontend using `hasSolution_iff_coqPCP`
  -- 4. Use `instanceToStack_mpcp_to_pcp` to tie the mapped structures together!
  sorry

end PCP
